// lib/billing/plans.js
/**
 * Authoritative Plan Configuration for GabbarInfo AI
 * 
 * Defines the official modular subscription tiers, pricing in INR,
 * asset-slot limits, per-asset isolated quotas, and feature entitlements.
 * 
 * SERVER-SIDE SOURCE OF TRUTH.
 * The frontend and all backend services MUST consume this configuration.
 */

export const SUBSCRIPTION_PLANS = {
  // ==========================================
  // 1. ALL-IN-ONE GROWTH SUITES (TAB 2)
  // ==========================================
  suite_1: {
    id: "suite_1",
    category: "suite",
    name: "Solo Growth Engine (1 Business / Store)",
    priceINR: 4499,
    billingCycle: "monthly",
    description: "Complete AI marketing engine for 1 brand: 30 Social Posts (Daily Autopilot), 8 SEO Blogs, 25 Shopify Product Descs / 4 Pages, 4 Ad Campaigns (Google+Meta), and 1 Free GMB Profile.",
    limits: {
      maxWordPressSites: 1,
      maxShopifyStores: 1,
      maxSocialBrands: 1,
      maxAdAccounts: 1,
      maxGmbLocations: 1,
      maxBusinesses: 1,
    },
    features: {
      SEO: true,
      SEO_AUTOPILOT: true,
      SOCIAL: true,
      SOCIAL_AUTOPILOT: true,
      META_ADS: true,
      GOOGLE_ADS: true,
      GMB: true,
      GMB_AUTOPILOT: true,
      IMAGE_GENERATION: true,
      AI_CHAT: true,
      AGENT_EXECUTION: true,
    },
    perAssetQuotas: {
      blogsPerSite: 8,
      postsPerBrand: 30,
      googleAdsPerAccount: 2,
      metaAdsPerAccount: 2,
      gmbLocations: 1,
    },
    quotas: {
      SEO_ARTICLE: 8,
      PRODUCT_DESC: 25,
      PAGE_CREATION: 4,
      SOCIAL_POST: 30,
      GOOGLE_CAMPAIGN: 2,
      META_CAMPAIGN: 2,
      IMAGE_GENERATION: 60,
      AI_QUERY: 200,
    },
    supportedCadences: {
      seo: ["weekly", "monthly", "custom"],
      social: ["daily", "alternate", "weekly", "custom"],
    },
  },

  suite_2: {
    id: "suite_2",
    category: "suite",
    name: "Pro Multi-Business Engine (Up to 3 Businesses / Stores)",
    priceINR: 8999,
    billingCycle: "monthly",
    description: "Multi-venture marketing engine for up to 3 businesses: 65 Social Posts, 16 SEO Blogs, 75 Shopify Product Descs / 10 Pages, 9 Ad Campaigns, and up to 3 GMB Profiles.",
    limits: {
      maxWordPressSites: 3,
      maxShopifyStores: 3,
      maxSocialBrands: 3,
      maxAdAccounts: 3,
      maxGmbLocations: 3,
      maxBusinesses: 3,
    },
    features: {
      SEO: true,
      SEO_AUTOPILOT: true,
      SOCIAL: true,
      SOCIAL_AUTOPILOT: true,
      META_ADS: true,
      GOOGLE_ADS: true,
      GMB: true,
      GMB_AUTOPILOT: true,
      IMAGE_GENERATION: true,
      AI_CHAT: true,
      AGENT_EXECUTION: true,
    },
    perAssetQuotas: {
      blogsPerSite: 16,
      postsPerBrand: 65,
      googleAdsPerAccount: 5,
      metaAdsPerAccount: 4,
      gmbLocations: 3,
    },
    quotas: {
      SEO_ARTICLE: 16,
      PRODUCT_DESC: 75,
      PAGE_CREATION: 10,
      SOCIAL_POST: 65,
      GOOGLE_CAMPAIGN: 5,
      META_CAMPAIGN: 4,
      IMAGE_GENERATION: 150,
      AI_QUERY: 500,
    },
    supportedCadences: {
      seo: ["daily", "weekly", "monthly", "custom"],
      social: ["daily", "alternate", "weekly", "custom"],
    },
  },

  suite_3: {
    id: "suite_3",
    category: "suite",
    name: "Agency Scale Powerhouse (Up to 8 Businesses / Stores)",
    priceINR: 14999,
    billingCycle: "monthly",
    description: "Full-scale agency powerhouse: up to 8 Social Brands (150 posts), 5 Websites/Stores (35 SEO blogs, 200 product descs / 25 pages), 15 Ad Campaigns, and 5 GMB Profiles.",
    limits: {
      maxWordPressSites: 5,
      maxShopifyStores: 5,
      maxSocialBrands: 8,
      maxAdAccounts: 8,
      maxGmbLocations: 5,
      maxBusinesses: 8,
    },
    features: {
      SEO: true,
      SEO_AUTOPILOT: true,
      SOCIAL: true,
      SOCIAL_AUTOPILOT: true,
      META_ADS: true,
      GOOGLE_ADS: true,
      GMB: true,
      GMB_AUTOPILOT: true,
      IMAGE_GENERATION: true,
      AI_CHAT: true,
      AGENT_EXECUTION: true,
    },
    perAssetQuotas: {
      blogsPerSite: 35,
      postsPerBrand: 150,
      googleAdsPerAccount: 8,
      metaAdsPerAccount: 7,
      gmbLocations: 5,
    },
    quotas: {
      SEO_ARTICLE: 35,
      PRODUCT_DESC: 200,
      PAGE_CREATION: 25,
      SOCIAL_POST: 150,
      GOOGLE_CAMPAIGN: 8,
      META_CAMPAIGN: 7,
      IMAGE_GENERATION: 300,
      AI_QUERY: 1200,
    },
    supportedCadences: {
      seo: ["daily", "weekly", "monthly", "custom"],
      social: ["daily", "alternate", "weekly", "custom"],
    },
  },

  // ==========================================
  // 2. STANDALONE WORDPRESS SEO SUITE
  // ==========================================
  seo_1: {
    id: "seo_1",
    category: "seo",
    name: "WP SEO Starter (1 Site)",
    priceINR: 1799,
    billingCycle: "monthly",
    description: "Autonomous WordPress SEO for 1 website: 4 High-Impact Blogs (Weekly), 2 SEO Service/Landing Pages, Auto-Social Syndication, 15 AI Images, and 60 Strategy Queries.",
    limits: {
      maxWordPressSites: 1,
      maxShopifyStores: 0,
      maxSocialBrands: 0,
      maxAdAccounts: 0,
      maxBusinesses: 1,
    },
    features: {
      SEO: true,
      SEO_AUTOPILOT: true,
      SOCIAL: false,
      SOCIAL_AUTOPILOT: false,
      META_ADS: false,
      GOOGLE_ADS: false,
      IMAGE_GENERATION: true,
      AI_CHAT: true,
      AGENT_EXECUTION: true,
    },
    perAssetQuotas: {
      blogsPerSite: 4,
    },
    quotas: {
      SEO_ARTICLE: 4,
      PAGE_CREATION: 2,
      PRODUCT_DESC: 0,
      SOCIAL_POST: 0,
      GOOGLE_CAMPAIGN: 0,
      META_CAMPAIGN: 0,
      IMAGE_GENERATION: 15,
      AI_QUERY: 60,
    },
    supportedCadences: {
      seo: ["weekly", "monthly", "custom"],
      social: [],
    },
  },

  seo_2: {
    id: "seo_2",
    category: "seo",
    name: "WP SEO Growth (1 Site)",
    priceINR: 3499,
    billingCycle: "monthly",
    description: "Accelerated WordPress SEO: 12 In-depth Blogs (~3/week), 6 SEO Service Pages, Auto-Social Syndication, 40 AI Images, and 150 Strategy Queries.",
    limits: {
      maxWordPressSites: 1,
      maxShopifyStores: 0,
      maxSocialBrands: 0,
      maxAdAccounts: 0,
      maxBusinesses: 1,
    },
    features: {
      SEO: true,
      SEO_AUTOPILOT: true,
      SOCIAL: false,
      SOCIAL_AUTOPILOT: false,
      META_ADS: false,
      GOOGLE_ADS: false,
      IMAGE_GENERATION: true,
      AI_CHAT: true,
      AGENT_EXECUTION: true,
    },
    perAssetQuotas: {
      blogsPerSite: 12,
    },
    quotas: {
      SEO_ARTICLE: 12,
      PAGE_CREATION: 6,
      PRODUCT_DESC: 0,
      SOCIAL_POST: 0,
      GOOGLE_CAMPAIGN: 0,
      META_CAMPAIGN: 0,
      IMAGE_GENERATION: 40,
      AI_QUERY: 150,
    },
    supportedCadences: {
      seo: ["daily", "weekly", "monthly", "custom"],
      social: [],
    },
  },

  seo_3: {
    id: "seo_3",
    category: "seo",
    name: "WP SEO Dominator (Up to 3 Sites)",
    priceINR: 6999,
    billingCycle: "monthly",
    description: "Authority SEO domination for up to 3 WordPress websites: 30 Daily/Split Blogs, 15 SEO Service Pages, 100 AI Images, and 400 Queries.",
    limits: {
      maxWordPressSites: 3,
      maxShopifyStores: 0,
      maxSocialBrands: 0,
      maxAdAccounts: 0,
      maxBusinesses: 3,
    },
    features: {
      SEO: true,
      SEO_AUTOPILOT: true,
      SOCIAL: false,
      SOCIAL_AUTOPILOT: false,
      META_ADS: false,
      GOOGLE_ADS: false,
      IMAGE_GENERATION: true,
      AI_CHAT: true,
      AGENT_EXECUTION: true,
    },
    perAssetQuotas: {
      blogsPerSite: 30,
    },
    quotas: {
      SEO_ARTICLE: 30,
      PAGE_CREATION: 15,
      PRODUCT_DESC: 0,
      SOCIAL_POST: 0,
      GOOGLE_CAMPAIGN: 0,
      META_CAMPAIGN: 0,
      IMAGE_GENERATION: 100,
      AI_QUERY: 400,
    },
    supportedCadences: {
      seo: ["daily", "weekly", "monthly", "custom"],
      social: [],
    },
  },

  // ==========================================
  // 3. STANDALONE SHOPIFY STORE SEO SUITE
  // ==========================================
  shopify_1: {
    id: "shopify_1",
    category: "shopify",
    name: "Shopify SEO Starter (1 Store)",
    priceINR: 1799,
    billingCycle: "monthly",
    description: "eCommerce SEO for 1 Shopify store: 4 In-stock Product Linked Blogs (Weekly), 15 Product Descriptions Optimized, 15 AI Images, and 60 Queries.",
    limits: {
      maxShopifyStores: 1,
      maxWordPressSites: 0,
      maxSocialBrands: 0,
      maxAdAccounts: 0,
      maxBusinesses: 1,
    },
    features: {
      SEO: true,
      SEO_AUTOPILOT: true,
      SOCIAL: false,
      SOCIAL_AUTOPILOT: false,
      META_ADS: false,
      GOOGLE_ADS: false,
      IMAGE_GENERATION: true,
      AI_CHAT: true,
      AGENT_EXECUTION: true,
    },
    perAssetQuotas: {
      blogsPerSite: 4,
    },
    quotas: {
      SEO_ARTICLE: 4,
      PRODUCT_DESC: 15,
      PAGE_CREATION: 0,
      SOCIAL_POST: 0,
      GOOGLE_CAMPAIGN: 0,
      META_CAMPAIGN: 0,
      IMAGE_GENERATION: 15,
      AI_QUERY: 60,
    },
    supportedCadences: {
      seo: ["weekly", "monthly", "custom"],
      social: [],
    },
  },

  shopify_2: {
    id: "shopify_2",
    category: "shopify",
    name: "Shopify SEO Growth (1 Store)",
    priceINR: 3499,
    billingCycle: "monthly",
    description: "Scale your store traffic: 12 Product-Linked Blogs (~3/week), 50 Catalog Product Descriptions, 40 AI Images, and 150 Queries.",
    limits: {
      maxShopifyStores: 1,
      maxWordPressSites: 0,
      maxSocialBrands: 0,
      maxAdAccounts: 0,
      maxBusinesses: 1,
    },
    features: {
      SEO: true,
      SEO_AUTOPILOT: true,
      SOCIAL: false,
      SOCIAL_AUTOPILOT: false,
      META_ADS: false,
      GOOGLE_ADS: false,
      IMAGE_GENERATION: true,
      AI_CHAT: true,
      AGENT_EXECUTION: true,
    },
    perAssetQuotas: {
      blogsPerSite: 12,
    },
    quotas: {
      SEO_ARTICLE: 12,
      PRODUCT_DESC: 50,
      PAGE_CREATION: 0,
      SOCIAL_POST: 0,
      GOOGLE_CAMPAIGN: 0,
      META_CAMPAIGN: 0,
      IMAGE_GENERATION: 40,
      AI_QUERY: 150,
    },
    supportedCadences: {
      seo: ["daily", "weekly", "monthly", "custom"],
      social: [],
    },
  },

  shopify_3: {
    id: "shopify_3",
    category: "shopify",
    name: "Shopify SEO Scale (Up to 3 Stores)",
    priceINR: 6999,
    billingCycle: "monthly",
    description: "Multi-store eCommerce domination: 30 Daily/Split Blogs, 150 Product Descriptions Optimization, 100 AI Images, and 400 Queries across up to 3 Shopify stores.",
    limits: {
      maxShopifyStores: 3,
      maxWordPressSites: 0,
      maxSocialBrands: 0,
      maxAdAccounts: 0,
      maxBusinesses: 3,
    },
    features: {
      SEO: true,
      SEO_AUTOPILOT: true,
      SOCIAL: false,
      SOCIAL_AUTOPILOT: false,
      META_ADS: false,
      GOOGLE_ADS: false,
      IMAGE_GENERATION: true,
      AI_CHAT: true,
      AGENT_EXECUTION: true,
    },
    perAssetQuotas: {
      blogsPerSite: 30,
    },
    quotas: {
      SEO_ARTICLE: 30,
      PRODUCT_DESC: 150,
      PAGE_CREATION: 0,
      SOCIAL_POST: 0,
      GOOGLE_CAMPAIGN: 0,
      META_CAMPAIGN: 0,
      IMAGE_GENERATION: 100,
      AI_QUERY: 400,
    },
    supportedCadences: {
      seo: ["daily", "weekly", "monthly", "custom"],
      social: [],
    },
  },

  // ==========================================
  // 4. STANDALONE SOCIAL MEDIA PLANNER (FB + IG)
  // ==========================================
  social_1: {
    id: "social_1",
    category: "social",
    name: "Social Solo (1 Brand)",
    priceINR: 599,
    billingCycle: "monthly",
    description: "Autonomous social media publishing for 1 brand (FB+IG): 15 Posts/mo (Weekly or Alternate cadence), 20 AI Images, and 50 Queries.",
    limits: {
      maxWordPressSites: 0,
      maxShopifyStores: 0,
      maxSocialBrands: 1,
      maxAdAccounts: 0,
      maxBusinesses: 1,
    },
    features: {
      SEO: false,
      SEO_AUTOPILOT: false,
      SOCIAL: true,
      SOCIAL_AUTOPILOT: true,
      META_ADS: false,
      GOOGLE_ADS: false,
      IMAGE_GENERATION: true,
      AI_CHAT: true,
      AGENT_EXECUTION: true,
    },
    perAssetQuotas: {
      postsPerBrand: 15,
    },
    quotas: {
      SEO_ARTICLE: 0,
      SOCIAL_POST: 15,
      GOOGLE_CAMPAIGN: 0,
      META_CAMPAIGN: 0,
      IMAGE_GENERATION: 20,
      AI_QUERY: 50,
    },
    supportedCadences: {
      seo: [],
      social: ["weekly_4", "weekly", "alternate", "custom"],
    },
  },

  social_2: {
    id: "social_2",
    category: "social",
    name: "Social Pro (1 Brand)",
    priceINR: 1199,
    billingCycle: "monthly",
    description: "Full Daily Autopilot for 1 brand (FB+IG): 30 Posts/mo (Daily posting), 40 AI Images, and 120 Queries.",
    limits: {
      maxWordPressSites: 0,
      maxShopifyStores: 0,
      maxSocialBrands: 1,
      maxAdAccounts: 0,
      maxBusinesses: 1,
    },
    features: {
      SEO: false,
      SEO_AUTOPILOT: false,
      SOCIAL: true,
      SOCIAL_AUTOPILOT: true,
      META_ADS: false,
      GOOGLE_ADS: false,
      IMAGE_GENERATION: true,
      AI_CHAT: true,
      AGENT_EXECUTION: true,
    },
    perAssetQuotas: {
      postsPerBrand: 30,
    },
    quotas: {
      SEO_ARTICLE: 0,
      SOCIAL_POST: 30,
      GOOGLE_CAMPAIGN: 0,
      META_CAMPAIGN: 0,
      IMAGE_GENERATION: 40,
      AI_QUERY: 120,
    },
    supportedCadences: {
      seo: [],
      social: ["daily", "alternate", "weekly_4", "weekly", "custom"],
    },
  },

  social_3: {
    id: "social_3",
    category: "social",
    name: "Social Multi-Brand (Up to 3 Brands)",
    priceINR: 2499,
    billingCycle: "monthly",
    description: "Multi-brand social publishing: up to 3 Brands, 65 Posts/mo flexible pool, 90 AI Images, and 250 Queries.",
    limits: {
      maxWordPressSites: 0,
      maxShopifyStores: 0,
      maxSocialBrands: 3,
      maxAdAccounts: 0,
      maxBusinesses: 3,
    },
    features: {
      SEO: false,
      SEO_AUTOPILOT: false,
      SOCIAL: true,
      SOCIAL_AUTOPILOT: true,
      META_ADS: false,
      GOOGLE_ADS: false,
      IMAGE_GENERATION: true,
      AI_CHAT: true,
      AGENT_EXECUTION: true,
    },
    perAssetQuotas: {
      postsPerBrand: 65,
    },
    quotas: {
      SEO_ARTICLE: 0,
      SOCIAL_POST: 65,
      GOOGLE_CAMPAIGN: 0,
      META_CAMPAIGN: 0,
      IMAGE_GENERATION: 90,
      AI_QUERY: 250,
    },
    supportedCadences: {
      seo: [],
      social: ["daily", "alternate", "weekly_4", "weekly", "custom"],
    },
  },

  social_4: {
    id: "social_4",
    category: "social",
    name: "Social Agency / Scale (Up to 8 Brands)",
    priceINR: 4999,
    billingCycle: "monthly",
    description: "Agency-scale social publishing: up to 8 Brands, 150 Posts/mo flexible pool, 200 AI Images, and 600 Queries.",
    limits: {
      maxWordPressSites: 0,
      maxShopifyStores: 0,
      maxSocialBrands: 8,
      maxAdAccounts: 0,
      maxBusinesses: 8,
    },
    features: {
      SEO: false,
      SEO_AUTOPILOT: false,
      SOCIAL: true,
      SOCIAL_AUTOPILOT: true,
      META_ADS: false,
      GOOGLE_ADS: false,
      IMAGE_GENERATION: true,
      AI_CHAT: true,
      AGENT_EXECUTION: true,
    },
    perAssetQuotas: {
      postsPerBrand: 150,
    },
    quotas: {
      SEO_ARTICLE: 0,
      SOCIAL_POST: 150,
      GOOGLE_CAMPAIGN: 0,
      META_CAMPAIGN: 0,
      IMAGE_GENERATION: 200,
      AI_QUERY: 600,
    },
    supportedCadences: {
      seo: [],
      social: ["daily", "alternate", "weekly_4", "weekly", "custom"],
    },
  },

  // ==========================================
  // 5. STANDALONE PERFORMANCE ADS ENGINE (+ FREE GMB)
  // ==========================================
  ads_1: {
    id: "ads_1",
    category: "ads",
    name: "Ads Starter (Up to 2 Businesses)",
    priceINR: 2199,
    billingCycle: "monthly",
    description: "High-ROI campaign launcher: 6 Campaigns/mo (flexible Google + Meta split across up to 2 businesses), Free GMB Profile Sync + AI Review Responder, 30 Ad Creatives, 100 Queries.",
    limits: {
      maxWordPressSites: 0,
      maxShopifyStores: 0,
      maxSocialBrands: 0,
      maxAdAccounts: 2,
      maxGmbLocations: 1,
      maxBusinesses: 2,
    },
    features: {
      SEO: false,
      SEO_AUTOPILOT: false,
      SOCIAL: false,
      SOCIAL_AUTOPILOT: false,
      META_ADS: true,
      GOOGLE_ADS: true,
      GMB: true,
      GMB_AUTOPILOT: true,
      IMAGE_GENERATION: true,
      AI_CHAT: true,
      AGENT_EXECUTION: true,
    },
    perAssetQuotas: {
      googleAdsPerAccount: 3,
      metaAdsPerAccount: 3,
      gmbLocations: 1,
    },
    quotas: {
      SEO_ARTICLE: 0,
      SOCIAL_POST: 0,
      GOOGLE_CAMPAIGN: 3,
      META_CAMPAIGN: 3,
      IMAGE_GENERATION: 30,
      AI_QUERY: 100,
    },
    supportedCadences: {
      seo: [],
      social: [],
    },
  },

  ads_2: {
    id: "ads_2",
    category: "ads",
    name: "Ads Pro (Up to 3 Businesses)",
    priceINR: 3499,
    billingCycle: "monthly",
    description: "Expanded campaign engine: 9 Campaigns/mo (flexible Google + Meta split across up to 3 businesses), Up to 2 Free GMB Profiles, 50 Ad Creatives, 200 Queries.",
    limits: {
      maxWordPressSites: 0,
      maxShopifyStores: 0,
      maxSocialBrands: 0,
      maxAdAccounts: 3,
      maxGmbLocations: 2,
      maxBusinesses: 3,
    },
    features: {
      SEO: false,
      SEO_AUTOPILOT: false,
      SOCIAL: false,
      SOCIAL_AUTOPILOT: false,
      META_ADS: true,
      GOOGLE_ADS: true,
      GMB: true,
      GMB_AUTOPILOT: true,
      IMAGE_GENERATION: true,
      AI_CHAT: true,
      AGENT_EXECUTION: true,
    },
    perAssetQuotas: {
      googleAdsPerAccount: 5,
      metaAdsPerAccount: 4,
      gmbLocations: 2,
    },
    quotas: {
      SEO_ARTICLE: 0,
      SOCIAL_POST: 0,
      GOOGLE_CAMPAIGN: 5,
      META_CAMPAIGN: 4,
      IMAGE_GENERATION: 50,
      AI_QUERY: 200,
    },
    supportedCadences: {
      seo: [],
      social: [],
    },
  },

  ads_3: {
    id: "ads_3",
    category: "ads",
    name: "Ads Scale (Up to 5 Businesses)",
    priceINR: 5999,
    billingCycle: "monthly",
    description: "Agency-scale ad manager: 15 Campaigns/mo across up to 5 businesses, Up to 5 Free GMB Profiles, 100 Ad Creatives, 450 Queries.",
    limits: {
      maxWordPressSites: 0,
      maxShopifyStores: 0,
      maxSocialBrands: 0,
      maxAdAccounts: 5,
      maxGmbLocations: 5,
      maxBusinesses: 5,
    },
    features: {
      SEO: false,
      SEO_AUTOPILOT: false,
      SOCIAL: false,
      SOCIAL_AUTOPILOT: false,
      META_ADS: true,
      GOOGLE_ADS: true,
      GMB: true,
      GMB_AUTOPILOT: true,
      IMAGE_GENERATION: true,
      AI_CHAT: true,
      AGENT_EXECUTION: true,
    },
    perAssetQuotas: {
      googleAdsPerAccount: 8,
      metaAdsPerAccount: 7,
      gmbLocations: 5,
    },
    quotas: {
      SEO_ARTICLE: 0,
      SOCIAL_POST: 0,
      GOOGLE_CAMPAIGN: 8,
      META_CAMPAIGN: 7,
      IMAGE_GENERATION: 100,
      AI_QUERY: 450,
    },
    supportedCadences: {
      seo: [],
      social: [],
    },
  },

  // ==========================================
  // 6. STANDALONE LOCAL MAPS & REVIEW BOOSTER
  // ==========================================
  gmb_1: {
    id: "gmb_1",
    category: "gmb",
    name: "Local Maps & Review Booster",
    priceINR: 499,
    billingCycle: "monthly",
    description: "Autonomous Google Maps & Local SEO: 1 Verified GMB Profile Sync, 5-min AI Review Responder, Weekly Maps & Search Tracker, 4 Local GMB Posts, 10 Images, and 50 Queries.",
    limits: {
      maxWordPressSites: 0,
      maxShopifyStores: 0,
      maxSocialBrands: 0,
      maxAdAccounts: 0,
      maxGmbLocations: 1,
      maxBusinesses: 1,
    },
    features: {
      SEO: false,
      SEO_AUTOPILOT: false,
      SOCIAL: false,
      SOCIAL_AUTOPILOT: false,
      META_ADS: false,
      GOOGLE_ADS: false,
      GMB: true,
      GMB_AUTOPILOT: true,
      IMAGE_GENERATION: true,
      AI_CHAT: true,
      AGENT_EXECUTION: true,
    },
    perAssetQuotas: {
      gmbLocations: 1,
    },
    quotas: {
      SEO_ARTICLE: 0,
      SOCIAL_POST: 0,
      GOOGLE_CAMPAIGN: 0,
      META_CAMPAIGN: 0,
      IMAGE_GENERATION: 10,
      AI_QUERY: 50,
    },
    supportedCadences: {
      seo: [],
      social: [],
    },
  },

  // ==========================================
  // 7. CROSS-CHANNEL POWER BUNDLES
  // ==========================================
  bundle_gads_gmb: {
    id: "bundle_gads_gmb",
    category: "bundle",
    name: "Google Omnipresence (Ads + Maps)",
    priceINR: 1999,
    billingCycle: "monthly",
    description: "Dominate Google High-Intent Search: Run Google Search ads featuring your verified Google Maps pin, store address, 5-star ratings, direct call button + 1 GMB profile.",
    limits: {
      maxWordPressSites: 0,
      maxSocialBrands: 0,
      maxAdAccounts: 1,
      maxGmbLocations: 1,
      maxBusinesses: 1,
    },
    features: {
      SEO: false,
      SEO_AUTOPILOT: false,
      SOCIAL: false,
      SOCIAL_AUTOPILOT: false,
      META_ADS: false,
      GOOGLE_ADS: true,
      GMB: true,
      GMB_AUTOPILOT: true,
      IMAGE_GENERATION: true,
      AI_CHAT: true,
      AGENT_EXECUTION: true,
    },
    perAssetQuotas: {
      googleAdsPerAccount: 2,
      metaAdsPerAccount: 0,
      gmbLocations: 1,
    },
    quotas: {
      SEO_ARTICLE: 0,
      SOCIAL_POST: 0,
      GOOGLE_CAMPAIGN: 2,
      META_CAMPAIGN: 0,
      IMAGE_GENERATION: 15,
      AI_QUERY: 200,
    },
    supportedCadences: {
      seo: [],
      social: [],
    },
  },

  bundle_seo_gmb: {
    id: "bundle_seo_gmb",
    category: "bundle",
    name: "Complete Search Dominance (SEO + Maps)",
    priceINR: 1999,
    billingCycle: "monthly",
    description: "Dominate both Google Organic Web Search and the Google Maps Local 3-Pack simultaneously: 1 WordPress site (30 daily AI blogs) + 1 GMB Profile with AI review responder.",
    limits: {
      maxWordPressSites: 1,
      maxSocialBrands: 0,
      maxAdAccounts: 0,
      maxGmbLocations: 1,
      maxBusinesses: 1,
    },
    features: {
      SEO: true,
      SEO_AUTOPILOT: true,
      SOCIAL: false,
      SOCIAL_AUTOPILOT: false,
      META_ADS: false,
      GOOGLE_ADS: false,
      GMB: true,
      GMB_AUTOPILOT: true,
      IMAGE_GENERATION: true,
      AI_CHAT: true,
      AGENT_EXECUTION: true,
    },
    perAssetQuotas: {
      blogsPerSite: 30,
      gmbLocations: 1,
    },
    quotas: {
      SEO_ARTICLE: 30,
      SOCIAL_POST: 0,
      GOOGLE_CAMPAIGN: 0,
      META_CAMPAIGN: 0,
      IMAGE_GENERATION: 30,
      AI_QUERY: 200,
    },
    supportedCadences: {
      seo: ["daily", "weekly", "monthly", "custom"],
      social: [],
    },
  },

  // ==========================================
  // 8. POWER SAMPLER TRIAL PACK (₹99)
  // ==========================================
  trial_99: {
    id: "trial_99",
    category: "trial",
    name: "Power Sampler Trial Pack",
    priceINR: 99,
    billingCycle: "trial_7d",
    description: "Hands-on test pack: 2 SEO Blogs, 2 Social Media Posts (FB+IG), 2 GMB AI Review Replies, 2 AI Images, and 10 Strategy Queries (7-day access).",
    limits: {
      maxWordPressSites: 1,
      maxSocialBrands: 1,
      maxAdAccounts: 0,
      maxGmbLocations: 1,
      maxBusinesses: 1,
    },
    features: {
      SEO: true,
      SEO_AUTOPILOT: false, // Locked for sampler: on-demand manual test only
      SOCIAL: true,
      SOCIAL_AUTOPILOT: false, // Locked for sampler: on-demand manual test only
      META_ADS: false,
      GOOGLE_ADS: false,
      GMB: true,
      GMB_AUTOPILOT: false, // Locked for sampler: on-demand manual test only
      IMAGE_GENERATION: true,
      AI_CHAT: true,
      AGENT_EXECUTION: true,
    },
    perAssetQuotas: {
      blogsPerSite: 2,
      postsPerBrand: 2,
      googleAdsPerAccount: 0,
      metaAdsPerAccount: 0,
      gmbLocations: 1,
    },
    quotas: {
      SEO_ARTICLE: 2,
      SOCIAL_POST: 2,
      GOOGLE_CAMPAIGN: 0,
      META_CAMPAIGN: 0,
      IMAGE_GENERATION: 2,
      AI_QUERY: 10,
    },
    supportedCadences: {
      seo: [],
      social: [],
    },
  },

  none: {
    id: "none",
    category: "trial",
    name: "Free Explorer (No Active Plan)",
    priceINR: 0,
    billingCycle: "none",
    description: "Free explorer mode: 5 AI queries and 1 AI image generation.",
    limits: {
      maxWordPressSites: 0,
      maxSocialBrands: 0,
      maxAdAccounts: 0,
      maxGmbLocations: 0,
      maxBusinesses: 1,
    },
    features: {
      SEO: false,
      SEO_AUTOPILOT: false,
      SOCIAL: false,
      SOCIAL_AUTOPILOT: false,
      META_ADS: false,
      GOOGLE_ADS: false,
      GMB: false,
      GMB_AUTOPILOT: false,
      IMAGE_GENERATION: true,
      AI_CHAT: true,
      AGENT_EXECUTION: false,
    },
    perAssetQuotas: {
      blogsPerSite: 0,
      postsPerBrand: 0,
      googleAdsPerAccount: 0,
      metaAdsPerAccount: 0,
      gmbLocations: 0,
    },
    quotas: {
      SEO_ARTICLE: 0,
      SOCIAL_POST: 0,
      GOOGLE_CAMPAIGN: 0,
      META_CAMPAIGN: 0,
      IMAGE_GENERATION: 1,
      AI_QUERY: 5,
    },
    supportedCadences: {
      seo: [],
      social: [],
    },
  },

  // ==========================================
  // 9. STANDALONE CINEMATIC LONG-FORM VIDEO PLANS
  // ==========================================
  video_creator: {
    id: "video_creator",
    category: "video",
    name: "Creator Studio (1-2 Min Videos)",
    priceINR: 1499,
    billingCycle: "monthly",
    description: "Cinematic AI video creation for solo & duo characters. Up to 2-minute videos, 1080p Full HD, 25 monthly minutes.",
    limits: {
      maxVideoMinutes: 25,
      maxCharactersPerScene: 2,
      maxVideoDurationSec: 120,
      maxBusinesses: 1,
    },
    features: {
      VIDEO: true,
      VIDEO_LONG_FORM: true,
      MULTI_CHARACTER: true,
      HD_1080P: true,
      IMAGE_GENERATION: true,
      AI_CHAT: true,
    },
    perAssetQuotas: {
      videoMinutes: 25,
      maxCharacters: 2,
      maxDurationMinutes: 2,
    },
    quotas: {
      VIDEO_MINUTES: 25,
      IMAGE_GENERATION: 50,
      AI_QUERY: 200,
    },
    supportedCadences: {
      video: ["on-demand", "scheduled"],
    },
  },

  video_pro: {
    id: "video_pro",
    category: "video",
    name: "Pro Production Studio (1-3 Min Videos)",
    priceINR: 3499,
    billingCycle: "monthly",
    badge: "Most Popular",
    description: "Cinematic ensemble storytelling with up to 3 distinct character voices. Up to 3-minute videos, 1080p, 70 monthly minutes, priority GPU queue.",
    limits: {
      maxVideoMinutes: 70,
      maxCharactersPerScene: 3,
      maxVideoDurationSec: 180,
      maxBusinesses: 2,
    },
    features: {
      VIDEO: true,
      VIDEO_LONG_FORM: true,
      MULTI_CHARACTER: true,
      HD_1080P: true,
      PRIORITY_QUEUE: true,
      IMAGE_GENERATION: true,
      AI_CHAT: true,
    },
    perAssetQuotas: {
      videoMinutes: 70,
      maxCharacters: 3,
      maxDurationMinutes: 3,
    },
    quotas: {
      VIDEO_MINUTES: 70,
      IMAGE_GENERATION: 150,
      AI_QUERY: 500,
    },
    supportedCadences: {
      video: ["on-demand", "scheduled"],
    },
  },

  video_cinema: {
    id: "video_cinema",
    category: "video",
    name: "Cinema & Agency Scale (1-5 Min Videos)",
    priceINR: 7999,
    billingCycle: "monthly",
    badge: "Maximum Power",
    description: "Full-scale cinematic studio. Unlimited characters, up to 5-minute videos, 200 monthly minutes, ultra-priority GPU rendering & commercial license.",
    limits: {
      maxVideoMinutes: 200,
      maxCharactersPerScene: 10,
      maxVideoDurationSec: 300,
      maxBusinesses: 5,
    },
    features: {
      VIDEO: true,
      VIDEO_LONG_FORM: true,
      MULTI_CHARACTER: true,
      HD_1080P: true,
      PRIORITY_QUEUE: true,
      COMMERCIAL_LICENSE: true,
      IMAGE_GENERATION: true,
      AI_CHAT: true,
    },
    perAssetQuotas: {
      videoMinutes: 200,
      maxCharacters: 10,
      maxDurationMinutes: 5,
    },
    quotas: {
      VIDEO_MINUTES: 200,
      IMAGE_GENERATION: 500,
      AI_QUERY: 2000,
    },
    supportedCadences: {
      video: ["on-demand", "scheduled"],
    },
  },

  // Standalone Pay-As-You-Go Packs
  video_pack_1min: {
    id: "video_pack_1min",
    category: "video_pack",
    name: "1-Minute Cinematic Video Pack",
    priceINR: 99,
    billingCycle: "one_time",
    description: "Single 1-Minute 1080p Cinematic AI Video with up to 2 characters.",
    limits: { maxVideoMinutes: 1, maxCharactersPerScene: 2, maxVideoDurationSec: 60, maxBusinesses: 1 },
    features: { VIDEO: true, VIDEO_LONG_FORM: true, HD_1080P: true },
    quotas: { VIDEO_MINUTES: 1 },
  },
  video_pack_2min: {
    id: "video_pack_2min",
    category: "video_pack",
    name: "2-Minute Cinematic Video Pack",
    priceINR: 189,
    billingCycle: "one_time",
    description: "Single 2-Minute 1080p Cinematic AI Video with up to 2 characters.",
    limits: { maxVideoMinutes: 2, maxCharactersPerScene: 2, maxVideoDurationSec: 120, maxBusinesses: 1 },
    features: { VIDEO: true, VIDEO_LONG_FORM: true, HD_1080P: true },
    quotas: { VIDEO_MINUTES: 2 },
  },
  video_pack_3min: {
    id: "video_pack_3min",
    category: "video_pack",
    name: "3-Minute Cinematic Video Pack",
    priceINR: 279,
    billingCycle: "one_time",
    description: "Single 3-Minute 1080p Cinematic AI Video with up to 3 characters.",
    limits: { maxVideoMinutes: 3, maxCharactersPerScene: 3, maxVideoDurationSec: 180, maxBusinesses: 1 },
    features: { VIDEO: true, VIDEO_LONG_FORM: true, HD_1080P: true },
    quotas: { VIDEO_MINUTES: 3 },
  },
  video_pack_5min: {
    id: "video_pack_5min",
    category: "video_pack",
    name: "5-Minute Cinematic Video Pack",
    priceINR: 449,
    billingCycle: "one_time",
    description: "Single 5-Minute 1080p Cinematic AI Video with up to 5 characters.",
    limits: { maxVideoMinutes: 5, maxCharactersPerScene: 5, maxVideoDurationSec: 300, maxBusinesses: 1 },
    features: { VIDEO: true, VIDEO_LONG_FORM: true, HD_1080P: true },
    quotas: { VIDEO_MINUTES: 5 },
  },

  // ==========================================
  // 10. BACKWARD COMPATIBILITY ALIASES
  // ==========================================
  try: {
    id: "try",
    category: "trial",
    name: "Free Explorer (No Active Plan)",
    priceINR: 0,
    billingCycle: "none",
    description: "Free explorer mode: 5 AI queries and 1 AI image generation.",
    limits: {
      maxWordPressSites: 0,
      maxSocialBrands: 0,
      maxAdAccounts: 0,
      maxGmbLocations: 0,
      maxBusinesses: 1,
    },
    features: {
      SEO: false,
      SEO_AUTOPILOT: false,
      SOCIAL: false,
      SOCIAL_AUTOPILOT: false,
      META_ADS: false,
      GOOGLE_ADS: false,
      GMB: false,
      GMB_AUTOPILOT: false,
      IMAGE_GENERATION: true,
      AI_CHAT: true,
      AGENT_EXECUTION: false,
    },
    perAssetQuotas: {
      blogsPerSite: 0,
      postsPerBrand: 0,
      googleAdsPerAccount: 0,
      metaAdsPerAccount: 0,
      gmbLocations: 0,
    },
    quotas: {
      SEO_ARTICLE: 0,
      SOCIAL_POST: 0,
      GOOGLE_CAMPAIGN: 0,
      META_CAMPAIGN: 0,
      IMAGE_GENERATION: 1,
      AI_QUERY: 5,
    },
    supportedCadences: {
      seo: [],
      social: [],
    },
  },
  agency: {
    id: "agency",
    category: "suite",
    name: "Unlimited Agency & Super Admin",
    priceINR: 0,
    billingCycle: "monthly",
    description: "Unlimited master tier with unrestricted access to all marketing, SEO, social, video, and ads features.",
    limits: {
      maxWordPressSites: 999,
      maxSocialBrands: 999,
      maxAdAccounts: 999,
      maxGmbLocations: 999,
      maxBusinesses: 999,
      maxVideoMinutes: 9999,
      maxCharactersPerScene: 10,
      maxVideoDurationSec: 600,
    },
    features: {
      SEO: true,
      SEO_AUTOPILOT: true,
      SOCIAL: true,
      SOCIAL_AUTOPILOT: true,
      META_ADS: true,
      GOOGLE_ADS: true,
      GMB: true,
      GMB_AUTOPILOT: true,
      IMAGE_GENERATION: true,
      AI_CHAT: true,
      AGENT_EXECUTION: true,
      VIDEO: true,
      VIDEO_LONG_FORM: true,
      MULTI_CHARACTER: true,
      HD_1080P: true,
      PRIORITY_QUEUE: true,
      COMMERCIAL_LICENSE: true,
    },
    perAssetQuotas: {
      blogsPerSite: 9999,
      postsPerBrand: 9999,
      googleAdsPerAccount: 9999,
      metaAdsPerAccount: 9999,
      gmbLocations: 999,
      videoMinutes: 9999,
      maxCharacters: 10,
      maxDurationMinutes: 10,
    },
    quotas: {
      SEO_ARTICLE: 9999,
      SOCIAL_POST: 9999,
      GOOGLE_CAMPAIGN: 9999,
      META_CAMPAIGN: 9999,
      IMAGE_GENERATION: 9999,
      AI_QUERY: 99999,
      VIDEO_MINUTES: 9999,
    },
    supportedCadences: {
      seo: ["daily", "weekly", "monthly", "custom"],
      social: ["daily", "alternate", "weekly_4", "weekly", "custom"],
      video: ["on-demand", "scheduled"],
    },
  },
};

// Aliases for legacy plan IDs
SUBSCRIPTION_PLANS.unlimited_owner = SUBSCRIPTION_PLANS.agency;
SUBSCRIPTION_PLANS.owner = SUBSCRIPTION_PLANS.agency;
SUBSCRIPTION_PLANS.starter = SUBSCRIPTION_PLANS.suite_1;
SUBSCRIPTION_PLANS.growth = SUBSCRIPTION_PLANS.suite_2;
SUBSCRIPTION_PLANS.business = SUBSCRIPTION_PLANS.suite_3;
SUBSCRIPTION_PLANS.agency_scale = SUBSCRIPTION_PLANS.suite_3;
SUBSCRIPTION_PLANS.social_scale = SUBSCRIPTION_PLANS.social_4;
SUBSCRIPTION_PLANS.pro_30d = SUBSCRIPTION_PLANS.none;
SUBSCRIPTION_PLANS.sampler = SUBSCRIPTION_PLANS.trial_99;
SUBSCRIPTION_PLANS["trial-99"] = SUBSCRIPTION_PLANS.trial_99;

export const DEFAULT_PLAN_ID = "none";

/**
 * Returns plan configuration by ID or falls back to 'try'.
 */
export function getPlanConfig(planId) {
  const normId = (planId || "").toLowerCase().trim();
  return SUBSCRIPTION_PLANS[normId] || SUBSCRIPTION_PLANS[DEFAULT_PLAN_ID];
}

/**
 * Error codes mandated by specification
 */
export const ENTITLEMENT_ERROR_CODES = {
  FEATURE_NOT_INCLUDED: "FEATURE_NOT_INCLUDED",
  MONTHLY_QUOTA_EXHAUSTED: "MONTHLY_QUOTA_EXHAUSTED",
  RESOURCE_LIMIT_REACHED: "RESOURCE_LIMIT_REACHED",
  SUBSCRIPTION_INACTIVE: "SUBSCRIPTION_INACTIVE",
  BUSINESS_ACCESS_DENIED: "BUSINESS_ACCESS_DENIED",
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RATE_LIMITED: "RATE_LIMITED",
  EXECUTION_ALREADY_IN_PROGRESS: "EXECUTION_ALREADY_IN_PROGRESS",
  PROVIDER_EXECUTION_FAILED: "PROVIDER_EXECUTION_FAILED",
  INSUFFICIENT_INTERNAL_CREDIT: "INSUFFICIENT_INTERNAL_CREDIT",
};
